implemented loading data from server
The-REACTive-DOMinators/react_catalog pull request #11
Opened 2023-06-11 23:42 UTC by Stambuliak

Implemented method of loading phones from back server.

2023-06-12 06:05 UTC, VenomMB requested changes
This is not a completed task fully, because you also need to load phones from API.
![image](https://github.com/The-REACTive-DOMinators/react_catalog/assets/106397016/2c102d07-c738-4643-b32a-5ceb21e63258)

2023-06-12 14:34 UTC, VenomMB requested changes
Add API function.

2023-06-13 16:21 UTC, Anna-Kuzmenko commented on src/services/fetchPhones.ts
> +}
Do we need this delay?

2023-06-13 16:43 UTC, Anna-Kuzmenko approved these changes
:fire:

2023-06-13 16:49 UTC, merged