Create card
The-REACTive-DOMinators/react_catalog pull request #12
Opened 2023-06-12 13:36 UTC by Anna-Kuzmenko

2023-06-12 14:20 UTC, VenomMB requested changes
Also, I think you can split this file, into small components. For example, buttons

2023-06-12 14:20 UTC, VenomMB commented on src/components/Card/Card.scss
> +      @include prise;
price

2023-06-12 14:20 UTC, VenomMB commented on src/components/Card/Card.scss
> +    &--discountPrise {
price

2023-06-12 14:20 UTC, VenomMB commented on src/components/Card/Card.tsx
> +export const Card: FC<Props> = ({ phone }) => {
use memo

2023-06-12 14:20 UTC, VenomMB commented on src/components/Card/Card.tsx
> +  };
useCallback

2023-06-12 14:20 UTC, VenomMB commented on src/components/Card/Card.tsx
> +        </a>
use NavLink

2023-06-12 14:20 UTC, VenomMB commented on src/components/Card/Card.tsx
> +        </a>
the same

2023-06-12 14:20 UTC, VenomMB commented on src/components/Card/Card.tsx
> +          <p>{screen}</p>
```suggestion
          <p className="card__char--category_name"> Screen </p>
          
          <p>{screen}</p>
```

2023-06-12 14:20 UTC, VenomMB commented on src/components/Card/Card.tsx
> +          <p>{ram}</p>
```suggestion
          <p className="card__char--category_name"> Capacity </p>
          
          <p>{capacity}</p>
        </div>

        <div className="card__char">
          <p className="card__char--category_name"> RAM </p>
          
          <p>{ram}</p>
```

2023-06-12 15:31 UTC, Anna-Kuzmenko commented on src/components/Card/Card.scss
> +      @include prise;
:see_no_evil:

2023-06-12 15:54 UTC, VenomMB requested changes

2023-06-12 15:54 UTC, VenomMB commented on src/components/Card/Card.tsx
> +          <FavoriteButton />
Please read about hoc and custom hooks, I think you can use one component button)

2023-06-13 07:21 UTC, VenomMB approved these changes
Good job

2023-06-13 07:21 UTC, merged