add photo block
The-REACTive-DOMinators/react_catalog pull request #20
Opened 2023-06-14 12:01 UTC by iHateAntichrist

https://prnt.sc/p1dXNijOfmTk

2023-06-14 13:03 UTC, Stambuliak commented on src/components/PhotosBlock/PhotosBlock.tsx
> +  // }, []);
do we need this?

2023-06-14 13:46 UTC, Anna-Kuzmenko commented on src/components/PhotosBlock/PhotosBlock.scss
> +  height: 471px;
You don't need this styles, it should be grid

2023-06-14 13:48 UTC, Anna-Kuzmenko commented on src/components/PhotosBlock/PhotosBlock.scss
> +    height: 442px;
these styles only for desktop, we should start from phone

2023-06-14 13:50 UTC, Anna-Kuzmenko requested changes
Styles only for desktop version, you should start from phone version

2023-06-14 16:14 UTC, VenomMB requested changes

2023-06-15 07:47 UTC, VenomMB approved these changes

2023-06-15 07:48 UTC, merged